// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31KNk9-Ew7PAQ_N7SdKb9qd4Kruz4-2I',
    appId: '1:338649491517:web:f270a1df61e3ba3f0a6254',
    messagingSenderId: '338649491517',
    projectId: 'ecocart-ea359',
    authDomain: 'ecocart-ea359.firebaseapp.com',
    storageBucket: 'ecocart-ea359.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1SwXvJeAnkwhRwtQnv4UkNXuRD7tlSX4',
    appId: '1:338649491517:android:ee5bbd5ebcd7c9cf0a6254',
    messagingSenderId: '338649491517',
    projectId: 'ecocart-ea359',
    storageBucket: 'ecocart-ea359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRj8RuZuZ4D27w0pjThBe-vrSbEEwJPQ',
    appId: '1:338649491517:ios:043fa46e6fd7ac780a6254',
    messagingSenderId: '338649491517',
    projectId: 'ecocart-ea359',
    storageBucket: 'ecocart-ea359.firebasestorage.app',
    iosClientId: '338649491517-8knr6hbsd07iojje181ddq91fbipsmd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecocart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRj8RuZuZ4D27w0pjThBe-vrSbEEwJPQ',
    appId: '1:338649491517:ios:043fa46e6fd7ac780a6254',
    messagingSenderId: '338649491517',
    projectId: 'ecocart-ea359',
    storageBucket: 'ecocart-ea359.firebasestorage.app',
    iosClientId: '338649491517-8knr6hbsd07iojje181ddq91fbipsmd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecocart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB31KNk9-Ew7PAQ_N7SdKb9qd4Kruz4-2I',
    appId: '1:338649491517:web:8c65b1478841f99a0a6254',
    messagingSenderId: '338649491517',
    projectId: 'ecocart-ea359',
    authDomain: 'ecocart-ea359.firebaseapp.com',
    storageBucket: 'ecocart-ea359.firebasestorage.app',
  );
}
